P8105_hw2_hc3212
================
Hening cui
2021/10/3

## Problem 1

Read and clean the Mr. Trash Wheel sheet.

``` r
trash_wheel_df = 
  read_excel("./data/Trashwheel.xlsx", sheet = "Mr. Trash Wheel", range = "A2:N408") %>% 
  janitor::clean_names() %>% 
  drop_na(dumpster) %>% 
  mutate(sports_balls = as.integer(sports_balls))
```

Read and clean precipitation data for 2018 and 2019.

``` r
pre_2018_df = 
  read_excel("./data/Trashwheel.xlsx", sheet = "2018 Precipitation", range = "A2:B15") %>%
  janitor::clean_names() %>% 
  drop_na(month, total) %>% 
  mutate(year = 2018) %>% 
  relocate(year) 

pre_2019_df = 
  read_excel("./data/Trashwheel.xlsx", sheet = "2019 Precipitation", range = "A2:B15") %>%
  janitor::clean_names() %>% 
  drop_na(month, total) %>% 
  mutate(year = 2019) %>%
  relocate(year) 
```

Precipitation combine.

``` r
NPre_df= 
  bind_rows(pre_2018_df, pre_2019_df) %>% 
  mutate(month = month.name[month])
```

The first data set was generated by Mr. Trashwheel trash collector in
Baltimore, Maryland which include the information of trash entering,
colletion and dumpster storage. The dataset contains information on
dumpster, month, year, date, weight_tons, volume_cubic_yards,
plastic_bottles, polystyrene, cigarette_butts, glass_bottles,
grocery_bags, chip_bags, sports_balls, homes_powered. There are a total
of 344 rows in our final dataset.

The second data set was the month precipitation data in 2018 and 2019.
The dataset contains information on year, month, total. There are a
total of 18 rows in our final dataset.

-   The total precipitation in 2018 was 70.33 inches.
-   The median number of sports balls found in a dumpster in 2019 was
    8.5

## Problem 2

Read and clean pols-month.csv.

``` r
pols_month_df = 
  read_csv("./data/fivethirtyeight/pols-month.csv") %>% 
  janitor::clean_names() %>% 
  drop_na() %>% 
  separate(mon, into = c("year", "month", "day"), sep = "-") %>% 
  mutate(month = month.name[as.integer(month)]) 
```

    ## Rows: 822 Columns: 9

    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon

    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
pols_month_clean_df = 
  pivot_longer(
    pols_month_df, 
    prez_gop:rep_dem,
    names_to  = "president",
    values_to  = "values"
  ) %>% 
  filter(!president %in% c("prez_dem","prez_gop")) %>% 
  select(-day)
view(pols_month_clean_df)
```

Read and clean snp.csv.

``` r
snp_df = 
  read_csv("./data/fivethirtyeight/snp.csv") %>% 
  janitor::clean_names() %>% 
  drop_na() %>% 
  mutate(date = mdy(as.character(date))) %>% 
  separate(date, into = c("year", "month", "day"), sep = "-") %>% 
  mutate(month = month.name[as.integer(month)]) %>% 
  select(-day) %>% 
  arrange(year, month) %>% 
  relocate(year, month)
```

    ## Rows: 787 Columns: 2

    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close

    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
view(snp_df) 
```

Read and clean unemployment.csv.

``` r
unemployment_df = 
  read_csv("./data/fivethirtyeight/unemployment.csv") %>% 
  janitor::clean_names() %>% 
  drop_na() 
```

    ## Rows: 68 Columns: 13

    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec

    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
unemployment_clean_df =
  pivot_longer(
    unemployment_df,
    jan:dec,
    names_to = "month",
    values_to = "percentage"
  ) 
view(unemployment_clean_df)
```

Join the datasets.

``` r
pols_tidy_df =
  pols_month_clean_df %>% 
  mutate(month = paste(month, "01", sep = "-"),
         month = as.Date(month, format = "%B-%d"),
         month = month(month)
         ) %>% 
  unite(date,year,month,sep = "-")
view(pols_tidy_df) 

snp_tidy_df =
  snp_df %>% 
  mutate(month = paste(month, "15", sep = "-"),
         month = as.Date(month, format = "%B-%d"),
         month = month(month)
         ) %>% 
  unite(date,year,month,sep = "-")
view(snp_tidy_df) 

unemployment_tidy_df =
  snp_df %>% 
  mutate(month = paste(month, "01", sep = "-"),
         month = as.Date(month, format = "%B-%d"),
         month = month(month)
         ) %>% 
  unite(date,year,month,sep = "-")
view(unemployment_tidy_df) 

pols_snp_df = 
  full_join(pols_tidy_df,snp_tidy_df,by = c("date" = "date")) 
view(pols_snp_df)

Fivethirtyeight_df =
  left_join(pols_snp_df,unemployment_tidy_df, by = c("date" = "date"))
Fivethirtyeight_df
```

    ## # A tibble: 5,161 × 5
    ##    date   president values close.x close.y
    ##    <chr>  <chr>      <dbl>   <dbl>   <dbl>
    ##  1 1947-1 gov_gop       23      NA      NA
    ##  2 1947-1 sen_gop       51      NA      NA
    ##  3 1947-1 rep_gop      253      NA      NA
    ##  4 1947-1 gov_dem       23      NA      NA
    ##  5 1947-1 sen_dem       45      NA      NA
    ##  6 1947-1 rep_dem      198      NA      NA
    ##  7 1947-2 gov_gop       23      NA      NA
    ##  8 1947-2 sen_gop       51      NA      NA
    ##  9 1947-2 rep_gop      253      NA      NA
    ## 10 1947-2 gov_dem       23      NA      NA
    ## # … with 5,151 more rows

The pols-month dataset describes the political landscape information of
the US from 1947 to 2015. There are a total of 4932 rows, and 3 columns
in our final dataset. The dataset contains information on date,
president, values.

The snp dataset shows the closing vales of the S&P stock index on the
associated month and year which from 1969 to 2068. There are a total of
787 rows, and 2 columns in our final dataset. The dataset contains
information on date, close.

The unemployment dataset presents the unemployment percentage of a
particular month from 1948 to 2014. There are a total of 804 rows, and 3
columns in our final dataset. The dataset contains information on year,
month, percentage.

The Fivethirtyeight dataset contains information on the political
landscape, stock performance, and unemployment percentages by merging
the previos 3 datasets together according to date. The time range from
1947 to 2068. There are a total of 5161 rows, and 5 columns in our final
dataset. The dataset contains information on date, president, values,
close.x, close.y.

## Problem 3

Read and clean the NYC Popular_Birth_Name.csv.

``` r
NYC_birthname_df = 
  read_csv("./data/Popular_Baby_Names.csv") %>% 
  janitor::clean_names() %>%  
  drop_na() %>%
  mutate(
    childs_first_name = toupper(childs_first_name), 
    ethnicity = gsub(
      c("BLACK NON HISP", "WHITE NON HISP", "ASIAN AND PACI"),
      c("BLACK NON HISPANIC", "WHITE NON HISPANIC", "ASIAN AND PACIFIC ISLANDER"),
      pull(.,ethnicity))) %>% 
  distinct()
```

    ## Rows: 19418 Columns: 6

    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (3): Gender, Ethnicity, Child's First Name
    ## dbl (3): Year of Birth, Count, Rank

    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

    ## Warning in gsub(c("BLACK NON HISP", "WHITE NON HISP", "ASIAN AND PACI"), :
    ## argument 'pattern' has length > 1 and only the first element will be used

    ## Warning in gsub(c("BLACK NON HISP", "WHITE NON HISP", "ASIAN AND PACI"), :
    ## argument 'replacement' has length > 1 and only the first element will be used

``` r
view(NYC_birthname_df)
```

Produce a well-structured, reader-friendly table showing the rank in
popularity of the name “Olivia” as a female baby name over time; this
should have rows for ethnicities and columns for year. Produce a similar
table showing the most popular name among male children over time.

Finally, for male, white non-hispanic children born in 2016, produce a
scatter plot showing the number of children with a name (y axis) against
the rank in popularity of that name (x axis).
